DELETE http://localhost:3003/api/blogs/65159ac749390cfc11a05430
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1MTU3NDFlMjIzNDQzMzg2ZGNmN2U0MyIsImlhdCI6MTY5NTkxNDQyNSwiZXhwIjoxNjk1OTE4MDI1fQ.OitmTNT1HSNIV1s9Oe_KCBPB_pF0yZM6YBNZO3ibDxk
